### ISSUE TITLE
Recipe Conflict Obsidian Sword

### ISSUE THREAD

**Issue by Minithra** [Vyraal1/Interaction#1]
The Actually Additions and the Tiny Progressions Obsidian Swords share a recipe... and unfortunately when you craft it you get the AA one, which has only 6 attack. The Tiny Progressions one has 10.

**Comment by Vyraal1** [comment]
Oh thanks for pointing that out, Obsidian sword wasn't supposed to be available this early. It's only in there because its for the mobs, I'll disable the recipe.
