### ISSUE TITLE
Item scrolling mod conflicts

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#13]
Pack version: v0.07
Mods involved: Item Scroller, Inventory Tweaks, Mouse Tweaks

Item scrolling between the player's inventory and other inventories, e.g. chests, is broken in situations where more than a single item is to be moved by scrolling. The situation can be partially alleviated by changing

    WheelScrollDirection=0

to

    WheelScrollDirection=1

in MouseTweaks.cfg. 

However, this results in 2 items being moved for every scroll tick. Further changing
    
    B:enableScrollingSingle=true

to
    
    B:enableScrollingSingle=false

in itemscroller.cfg produces the behaviour I expect (but not necessarily the intended behaviour).

There are other possible ways of editing the relevant configs to fix this issue, depending on intended behaviour. Note that changing shortcuts in InvTweaks.cfg seems to have no effect.

I know from my own testing of mods/packs that removing Mouse Tweaks and using the default configs for both Item Scroller and Inventory Tweaks will result in any conflicts disappearing.

 Alge

**Comment by Vyraal1** [comment]
Thanks for this, this was bugging me the entire time, I'll end up removing MouseTweaks probably as it seems the extra functionality isn't used much and leave it at only Item Scroller and Inventory Tweaks. I'll do testing tonight and see it it works for v0.08.

**Comment by Hjaldar** [comment]
Confirmed fixed in 0.08
