### ISSUE TITLE
Petal Apothecary recipe for sugar cane does not work

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#14]
Version: v0.07

I'm in Tier 1 and was hoping to add vector plates to my mob farm. It looks like vector plates should be craftable in Tier 1, except maybe for sugar (which doesn't appear in the Tier 1 progression image - intended or oversight?).

There is a recipe for sugar cane, added in Minecraft.zs, which requires 4 melon slices in Botania's Petal Apothecary. However, the recipe doesn't work as melon slices do not go into the Petal Apothecary - they just sit on top.

It seems the Petal Apothecary only accepts petals, runes and redstone root. If it is intended that sugar cane should be obtainable in Tier 1, then I would suggest the following Petal Apothecary recipe:

    mods.botania.Apothecary.addRecipe(<minecraft:reeds>, [<ore:petalLime>, <ore:petalLime>, <ore:petalGreen>, <ore:petalGreen>]);

Alge

**Comment by DJJBanx** [comment]
Thank you for the bug report and the suggestion, we will be using this recipe. Good Idea.
