### ISSUE TITLE
Quest Progression: DIAMONDS?

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#16]
Version: v0.07
Quest section: Sky - Main

I'd suggest placing the quest DIAMONDS? after Advanced Alchemy rather than Alchemy.

Players unfamiliar with the quirks of Sky Resources 2 who try to perform the recipe for Alchemical Diamond with Primus Alchemical Dust in the Fusion Table may receive nothing in return for their 6 blocks of coal (and may think this is due to a bug). The quest may also benefit from suggesting the player use Secundus Alchemical Dust when making Alchemical Diamond.

Alge

**Comment by DJJBanx** [comment]
Added information pertaining to the second tier alchemical dust to DIAMONDS? quest
