### ISSUE TITLE
Interaction v 0.03 server mode stopping due to NBGamingLib-1.12-2.9.1.jar error in console

### ISSUE THREAD

**Issue by thaimichael** [Vyraal1/Interaction#2]
I attempted to install v 0.03 to a test server setup on my desktop pc, pc specs Windows 10 pro 64bit, I7, 24GB ram, prior to pushing to my vps test server running mineOS on deb.
1.	Clean installation of forge server forge-1.12.2-14.23.1.2565 EULA accepted machine started and ran fine.
2.	java -Xmx4G -Xms2G -d64 -jar forge-1.12.2-14.23.1.2565-universal.jar nogui is in the start.bat file.
3.	Copied over the following folders from my curse v0.03 Interaction folder that runs correctly.  Config, mods, resources, and scripts folder.  I disabled Notes-1.12-1.1.1.jar client mod since it will crash in server mode.
4.	Using the start.bat file with command above started server.
5.	Server cycles completely through world generation then stops due to errors thrown up by the NBGamingLib-1.12-2.9.1.jar.  These errors are only shown in the console directly and not in the latest.log.
I am attaching the latest.log and the console output from my server.  If you need any other information or need me to try something let me know.
https://pastebin.com/cpfJaL2e  console output
https://pastebin.com/CUy6nTSx  latest.log

**Comment by thaimichael** [comment]
config/dimensionalcontrol/dimensions.cfg file below.
https://pastebin.com/qKLUW14z dimensions.cfg

**Comment by DJJBanx** [comment]
Mod Author has been notified and is working on a fix. Will be patched when mod updates.
