### ISSUE TITLE
[0.08] Missing/broken recipes stopping legitimate progression in Tier 2

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#29]
**_XU2 Scanner_**: Redstone gears are uncraftable due to missing **_redstone rod_** recipe.
**_Abyssalnite Rod_**: gated behind IE metal press - you mentioned this was intended to be used in the recipe for the gateway key.
**_XU2 Mechanical User_**: has no recipe if you decide it belongs in Tier 2
CM3 **_Miniaturization Field Projector_** (or its components): This is needed to make Reinforced Blast Bricks to make steel. It uses Basic Sensor and Basic Electric Piston in its recipe, both of which use steel (among other things) in their recipes
**_Basic Sensor_**: uses steel plate (requires steel), **_copper rod_** (requires metal press) and **_IC2 electronic circuit_** (no recipe - you may intend ore:basicCircuit here)
**_Basic Electric Piston_**: requires access to steel (gear, rod, plate) and Basic Motor
**_Basic Motor_**: requires access to steel (steel rod)

**Comment by Hjaldar** [comment]
XU2 **_Transfer Pipe_**: requires ore:glass (Natura glass) instead of ore:blockGlass (generic glass)

Forestry multifarms are not currently craftable/buildable. Some items have already been mentioned in the previous comment. Additions below (assuming steel is available).

**_Farm Gearbox_**: requires AA Auto-Breaker, which is not available due to the lack of Black Quartz oregen in Tier 2
**_Farm Valve_**: requires CoT **_Basic Valve_**, which is uncraftable, see below
**_Farm Control_**: requires AG **_Advanced Circuit_**, which uses Nether Quartz, currently unavailable in Tier 2
**_Basic Valve_**: requires **_Steel Bolt_** (no recipe), **_Steel Rotor_** (no recipe), **_Fluiduct_** (requires Basic Valve - loop!)

**Comment by Vyraal1** [comment]
**Redstone Rod**
![image](https://user-images.githubusercontent.com/26587049/35184225-a248f608-fdc0-11e7-8a7e-1fe5e99c860c.png)

**Abyssalnite Rod**

**Mechanical User**
I have decided it won't be in Tier 2, it's too useful, and too simple for one block at the moment. Ill have to add in a magical oriented recipe, for now I'll stick with Integrated Dynamics.

**Miniaturization Field Projeoctor**
![image](https://user-images.githubusercontent.com/26587049/35184391-eed7059e-fdc2-11e7-9261-2f844ba2e654.png)
Those are Refined iron plates, pending on whether it lets you craft 2 or 4 projectors.
**Basic Sensor**
![image](https://user-images.githubusercontent.com/26587049/35184394-00bf07c0-fdc3-11e7-9b3f-6c6420d8490b.png)
Those are Tin Plates and Copper Rods.
**Electronic Circuit**
![image](https://user-images.githubusercontent.com/26587049/35184405-1e420748-fdc3-11e7-9473-2573b1a8ae49.png)
Those are rubber electron tubes, I'm not sure if this is enough redstone.
**Farm Gearbox**
![image](https://user-images.githubusercontent.com/26587049/35185328-e03dc1c2-fdd0-11e7-9aba-2a0aea4d1752.png)

Uses an RF based block breaker from Industrial Foregoing,
**BlockBreaker**
![image](https://user-images.githubusercontent.com/26587049/35185331-fcfd3cca-fdd0-11e7-96a8-e4ba7494504d.png)
Uses a random things block breaker, available in Tier 1, those are Rubber Plates on the sides.

**Farm Valve**

**Basic Valve**
![image](https://user-images.githubusercontent.com/26587049/35185338-1852d7fa-fdd1-11e7-9868-98aff21104c0.png)

**Steel Bolt**
![image](https://user-images.githubusercontent.com/26587049/35185349-2e423538-fdd1-11e7-8334-cfce4d244b16.png)

Steel Rotor
![image](https://user-images.githubusercontent.com/26587049/35186463-b0af48b0-fde2-11e7-83e2-11dcd308e16d.png)
Just steel plates and steel rings

**Steel Ring**
![image](https://user-images.githubusercontent.com/26587049/35188402-dc03c282-fe02-11e7-85aa-15b1231e440b.png)

**Fluiduct**
![image](https://user-images.githubusercontent.com/26587049/35185323-d423b496-fdd0-11e7-85cc-cf194f8cb67a.png)
Copper plates and glass

**Farm Control**
Will be changed to have a redstone gear.
