### ISSUE TITLE
Empty crafting station creates a applied energistics charger

### ISSUE THREAD

**Issue by thaimichael** [Vyraal1/Interaction#33]
![image](https://user-images.githubusercontent.com/6601697/35241883-8db3e488-ffea-11e7-946e-b52c77e85445.png)

Applied Energistics charger appears in crafting station both in multiplayer and single player V0.09

Place a crafting station and open it output slot has a charger from applied energisics in it.

**Comment by Vyraal1** [comment]
Fixed in-dev
