### ISSUE TITLE
[0.095] Water extractor not giving 50mB per use

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#37]
I see you are aware of this. https://github.com/Bartz24/SkyResources/issues/119 No response from the dev yet.
 
SkyResources.zs lines 191 and 192 attempt to change the water extractor to give 50mB per use. This doesn't work because the original recipe is not removed and takes precedence over the added recipe which gives 50mB.

Changing the removeRecipe to use ore:treeLeaves did not fix this issue (zenscript error). Iterating through everything in ore:treeLeaves and removing them individually also did not work.

The relevant line of code that adds the unremoveable recipe is [here](https://github.com/Bartz24/SkyResources/blob/09f93720a3037280e92c61ef212b506377fbfbb1/src/main/java/com/bartz24/skyresources/registry/ModCrafting.java#L415). It uses the treeLeaves oredict entry. I think the recipe isn't being removed because removeRecipe only takes an [IItemStack as input](https://github.com/Bartz24/SkyResources/blob/a175be99338f5b108b6a20557891f00ab5a1b0ad/src/main/java/com/bartz24/skyresources/plugin/ctweaker/MTWaterExtractorExtractRecipe.java#L29). This looks unresolveable without dev input.

**Comment by Vyraal1** [comment]
Closing this issue to probably revisit at a later time, only really Bartz can fix this.
