### ISSUE TITLE
[0.095] Traveling Merchant from Primitive Mobs spawning on skyblock (breaks progression)

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#38]
A couple of times when going to my mob farm these mobs have spawned on my starter platform. They have villager trades and on one occasion I was able to trade carrots for emeralds and emeralds for iron. They seem to despawn eventually but I believe can be made permanent with an emerald block.

They can be disabled in primitivemobs.cfg. Also, this config file may need to be regenerated, as there seem to be duplicate entries

**Comment by Vyraal1** [comment]
Thanks for this, disabled the Traveling Merchant, might look into re-enabling him later down the line and relying on In Control to control his spawn instead. 

Regenerated config files for Void Island Control, Soulus, and Primitive Mobs as well while I'm at it.
