### ISSUE TITLE
Clay bucket is immediately used and breaks when right-clicking crucible with lava in it

### ISSUE THREAD

**Issue by Pandemoneus** [Vyraal1/Interaction#4]
When right-clicking a crucible that contains lava with a clay bucket and if the player has at least two clay buckets in the inventory, lava is extracted and immedatiely placed on the block relative to the face the player clicked on, breaking one of the buckets.
  
This is rather mod-related than pack-related, but I thought I would let you know.

**Comment by Pandemoneus** [comment]
Also seems to have happen with regular buckets. When you right-click the crucible the lava is taken out and immedatiely placed.

**Comment by davqvist** [comment]
https://github.com/Bartz24/SkyResources/issues/91

**Comment by thaimichael** [comment]
This is not really a modpack issue rather a mod issue, but the way I handle lava now is with a Tinkers's construct faucet on the crucible and put a TC tank under the faucet to receive the lava. Then you can either move to a smeltery or pick up from the tank with a bucket.

**Comment by Vyraal1** [comment]
Closing this issue, out of my hands at the moment and depends on Bartz having the time to fix it.
