### ISSUE TITLE
[0.095] Leaving or resetting islands (Void Island Control) results in empty inventory

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#41]
On servers players may use /island leave or /island reset to join another island or move the location of their island for other reasons. This results in an empty inventory.

voidislandcontrol.cfg has an option for setting starting inventory, so you may also be able to remove initial inventory. Although I am not sure whether void island control can handle the akashic tome.

**Comment by Vyraal1** [comment]
```
        # Reset players inventory with the starting inventory
        B:resetInventory=false
```

It can't handle the Akashtic tome unforunately, in this situation I'll just turn off the inventory reset.
