### ISSUE TITLE
[0.10] Crash on World Load due to misconfig in voidislandcontrol.cfg

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#42]
On singleplayer at least, this [crash](https://gist.github.com/Hjaldar/fd85309d8ec930a8f7b6dcd3f9fc7828) happens due to all islands being disabled in voidislandcontrol.cfg.

To fix, change B:enableGrassIsland=false to B:enableGrassIsland=true in voidislandcontrol.cfg

**Comment by Vyraal1** [comment]
Fixed in https://github.com/Vyraal1/Interaction/commit/12c1d7295cb8a310f849238085b3236500cd7aa5
