### ISSUE TITLE
[0.11] Small amounts of diamond ore (2-4 per lair) spawning in Ice and Fire underground dragon lairs

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#45]
There does not seem to be any way in the config file to disable this explicity. However, the chance can be reduced by increasing this value in iceandfire.cfg

    I:oreToStoneRatioForDragonCaves=1000

There are also diamonds in the chests in the loot table iceandfire/fire_dragon_cave

Also seems to be even smaller amounts of silver ore but I couldn't actually find one beyond seeing it in the results of /oredistribution

**Comment by Vyraal1** [comment]
Loottables were fixed to remove the diamonds and emeralds, but honestly not really sure how to fix this aside from just setting the number to 20,000, I'll try that instead.
