### ISSUE TITLE
[0.11] Primitive Mobs Lost Miner has nether quartz and diamond villager trades

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#46]
To disable, set

    B:"Enable Lost Miner"=false

in primitivemobs.cfg

**Comment by Vyraal1** [comment]
Instead of disabling it, I ended up using In Control to disable their spawning in dimension 0, 100 in the spawn.json in In Control configs. I'm hoping this mob will add at least some variety and life when they hit the larger cave systems in Tier 3.

```json
[
  {
    "mob": "primitivemobs.lost_miner",
    "dimension": [0, 100],
    "result": "deny"
  }
]

```
