### ISSUE TITLE
[0.12] Plant Matter to Charcoal Furnace Recipe 

### ISSUE THREAD

**Issue by Hjaldar** [Vyraal1/Interaction#48]
In Minecraft .zs:

`furnace.addRecipe(<minecraft:coal:1>, <skyresources:baseitemcomponent>*2);`

does not actually use 2 plant matter to make one charcoal, but shows it as doing so in JEI. I'd guess multiple items being consumed is not supported in furnace recipes.

**Comment by Vyraal1** [comment]
Looks like after talking to Shadows in Jared's discord the furnace has been hard coded to always consume one item at a time. I might've imagined it as being possible to use 2, in either case I'm not too hung up on this. I'll switch it to reflect only one.
