### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by davqvist** [Vyraal1/Interaction#6]
https://pastebin.com/3uYB7Ns6

**Comment by Vyraal1** [comment]
Some people on MMD said it's a concurrent issue, and don't got any better leads on what could cause this, and haven't seen this yet myself in testing the pack. I'll keep this here and see if we get more duplicate crash reports.

This crash was clientside right?

**Comment by davqvist** [comment]
Clientside yes

**Comment by DJJBanx** [comment]
This error is a result of a corrupted block in a certain chunk. To fix you can load the world in MCEdit and delete the chunk or block. I will close for now unless we get another duplicate crash report as Vyraal1 said.
