### ISSUE TITLE
Wooden Shears don't work with Ore Excavation

### ISSUE THREAD

**Issue by flashsugar** [Vyraal1/Interaction#60]
Check the video to see what happens

https://streamable.com/4cwmu

**Comment by Hjaldar** [comment]
Thanks for the report. Upon further testing all shears, except the Botania shears for some reason, only excavate a small area. This seems to be a [known issue](https://github.com/Funwayguy/OreExcavation/issues/5) and there seems to be little we can do about it on our end. Note that the same behavior occurs with the Sky Resources grinder on cobble, gravel, etc.

In practice this slows down getting leaves but the rate is still good, particularly now that the wooden shears have a high durability, and sufficient plant matter for early progression can be obtained relatively quickly.

**Comment by Vyraal1** [comment]
Checking the configs, I'm not exactly sure how to enable non-shape ore excavation, as this also seems to the default mode for shears for reasons unknown. Going to close this as I reached a deadend with this and while its suboptimal, like Alge said the rate of getting leaves is perfectly fine as it is.
