### ISSUE TITLE
Smeltery not correctly showing contents(possible bug with Tcon?)

### ISSUE THREAD

**Issue by flashsugar** [Vyraal1/Interaction#61]
The material texture for the contents of the smeltery is invisible.

![desktop screenshot 2018 02 26 - 18 17 24 08](https://user-images.githubusercontent.com/7461603/36703495-7ece111c-1b21-11e8-87fa-56b3c6a1fa26.png)

**Comment by Hjaldar** [comment]
I can't reproduce this. The texture shows for me.

1. Have you added any mods to the client? Is this running on a server?

2. If you type "@content" (without the quotes) in JEI, do you see the 13 fluids and their textures (Diluted Sulfuric Acid through Molten Rubber) that have been added to this pack? They should appear at the end of the list in JEI, so you may need to change pages.

**Comment by flashsugar** [comment]
I can see the 13 fluids but not any of the fluids in the smeltery. This is running on a server and i have not added any mods to the client.

**Comment by Vyraal1** [comment]
How big is that smeltery? 60 buckets is a lot of volume, im wondering if the smeltery GUI just glitched out or something. That's like 50 blocks of Reinforced Stone

**Comment by Hjaldar** [comment]
I made a big enough smeltery to hold over 60 buckets and still couldn't reproduce the issue. Nothing we can do from our end until we can reproduce this or get further information regarding exact conditions for reproduction.

**Comment by flashsugar** [comment]
It seemed to happen when I tried to step in the smeltery to make blood
