### ISSUE TITLE
Can't break furnaces with wooden pickaxes

### ISSUE THREAD

**Issue by Intipablo** [Vyraal1/Interaction#7]
I am unable to break my furnace with a wooden pickaxe, as it gets placed immediately into the furnace's fuel slot. I've tried holding both shift and control.

**Comment by Vyraal1** [comment]
Found the issue in Cyclic configs, fixed in next update.

>         # Stardew Furnaces: Quickly fill a furnace by hitting it with fuel or an item, or interact with an empty hand to pull out the results [Inspired by Stardew Valley.  Left click only] [default: true]
>         B:"Furnace Speed"=false
